prepare:
  test_size: 0.2
  random_state: 42

train:

  logistic_regression:
    C: 1.0
    max_iter: 1000

  random_forest:
    n_estimators: 200
    max_depth: 8
    random_state: 42

  xgboost:
    learning_rate: 0.1
    max_depth: 6
    n_estimators: 200
    random_state: 42

evaluate:
  min_accuracy: 0.70